### ISSUE TITLE
Tile offset between planes

### ISSUE THREAD

**Issue by tatsunootoshigo** [dciabrin/ngdevkit-examples#2]
Hi,
First of all great job for the TK!
I probably misunderstood something but can you tell me how you compute the offset between sprites in the CROM?
I thought to jump from a sprite to another the offset was number (horizontal tiles * number of vertical tiles).
Looks correct almost all the time but not betwwen the "back" and the "forest" planes in the example #05 where there is an additional 48 offset, but I can't figure out where it comes from. 

Back offset: 256
Forest offset: 256 + 24 * 7 **+ 48** = 472 // Why 48 here?
Front offset: 472 + 30 * 9 = 742 // This one seems logical to me :)

Is there some padding when generating the CROM maybe?

Thanks a lot for you help!

**Comment by dciabrin** [comment]
> I probably misunderstood something but can you tell me how you compute the offset between sprites in the CROM?
> I thought to jump from a sprite to another the offset was number (horizontal tiles * number of vertical tiles).

That's correct

> Looks correct almost all the time but not betwwen the "back" and the "forest" planes in the example #05 where there is an additional 48 offset, but I can't figure out where it comes from.

The misunderstanding comes from the fact that I didn't use all the tiles from the back image: it's 384 x 144 pixels, so 24 x 9 tiles. In the example I only used the first 7 lines of tiles because the other ones were hidden by the forest plane. The last two lines of tiles are 2 x 24 tiles = the 48 missing tiles in your computation :) 
I changed the example to use all the tiles and remove the ambiguity.

> Is there some padding when generating the CROM maybe?

No, the full image is converted to tiles and concatenated together in the output ROM.

I'm considering providing a dedicated tool in ngdevkit for tile/asset management, to ease tile management and not rely on magic hardcoded values in the code.

**Comment by tatsunootoshigo** [comment]
I got it thanks a lot :+1:
