### ISSUE TITLE
CROM size

### ISSUE THREAD

**Issue by tatsunootoshigo** [dciabrin/ngdevkit-examples#4]
Hi!
It is probably more a misunderstanding from my side than an issue, but how to allow larger CROMs?
I'm playing with the examples to learn the system limits and I noticed I'm producing C1 and C2 of 1.5Mb each. Even if I remove the truncation in the build process it clearly seems to me than tiles after the 1Mb limit are simply not displayed.
It seems, if I understand well, than I should be able to have multiple CROMs, ie. C1-C2, C3-C4, each of more than 8Mb and so on as needed. Do you know how they whould be linked together and how to use ROMs larger than 1Mb? Is that what is called bankswitching?
I also assume I would have same question for the VROM probably.
Thanks a lot for your help!

**Comment by dciabrin** [comment]
> Hi!
> It is probably more a misunderstanding from my side than an issue, but how to allow larger CROMs?
> I'm playing with the examples to learn the system limits and I noticed I'm producing C1 and C2 of 1.5Mb each. Even if I remove the truncation in the build process it clearly seems to me than tiles after the 1Mb limit are simply not displayed.

The neogeo hardware has a large address space for graphics data, but the way they are stored depend on the game cartridges. That is, in the cartridge, data access is routed to the right ROM that holds a specific part of the graphics address space.

Because of that multitude of layout, all the emulators out there need to have a list of known game cartridges, and the layout of their graphics ROM to be able to load it in memory.

That is the reason why the ROMs in ngdevkit-examples are called puzzledp.zip: I arbitrarily chose a game whose ROM layout is 128KB of program ROM, and 2x1MB of sprite ROM.   

If you want bigger sprite storage, you have to chose another ROM name known by gngeo, which is configured with bigger or more sprite ROMs.

> It seems, if I understand well, than I should be able to have multiple CROMs, ie. C1-C2, C3-C4, each of more than 8Mb and so on as needed. Do you know how they whould be linked together and how to use ROMs larger than 1Mb? Is that what is called bankswitching?

My understanding is that bankswitching is mainly used for program ROMs (68k and z80).  

> I also assume I would have same question for the VROM probably.

I don't think there's any sort of bakswitching for samples ROM either.
 
> Thanks a lot for your help!

**Comment by tatsunootoshigo** [comment]
Alright I understand! 
I was confused with bankswitching but yes you are right it only applies to 68k/z80.

I will have a look at gngeo game config and try it out with another game.
Does it means the "limitation" is only for emulators? I mean the real hardware could run a game with only 1 large CROM for example?

**Comment by dciabrin** [comment]
> Does it means the "limitation" is only for emulators? I mean the real hardware could run a game with only 1 large CROM for example?

It's at least a pair of CROM, because of the way sprite rom data are split in half and read by the hardware. But I don't think there has ever been an official ROM that was built with a single pair of chip that were sufficiently big to hold of the entire game graphics data.
